### ISSUE TITLE
custom styles not applying after save

### ISSUE THREAD

**Issue by jneilliii** [Birkbjo/OctoPrint-Themeify#10]
First and foremost, great work on this plugin.  I am however experiencing an issue.  One of my plugins uses the info class and I'm trying to use the customization section to apply a different background color to those rows.  The weird thing I'm experiencing is when I set the css it works while in the settings dialog (ie make change, look at my plugin's setting and changes are applied) but once you save and go back into the settings dialog the changes are no longer applied.  Here are some screenshots for comparison.

Customizations:
![image](https://user-images.githubusercontent.com/5249455/33234479-6f2c66b6-d1f5-11e7-941b-093f655eb497.png)

Before Save:
![image](https://user-images.githubusercontent.com/5249455/33234497-b171e5f0-d1f5-11e7-8ab6-c4b0353eed99.png)

After Save and Reopening Settings:
![image](https://user-images.githubusercontent.com/5249455/33234491-8f3032b2-d1f5-11e7-992d-f70fd03977e0.png)

**Comment by Birkbjo** [comment]
If you refresh the page, is it the results the same? I have a small fix for some related bug that may be related.

What plugin do you use and is it publically available?, would be nice to be able

**Comment by jneilliii** [comment]
I just did some additional testing and refreshing makes no difference.  I can however close the settings dialog and open it back up and the customizations are still applied, so it has something to do with the saving process.  My plugins are publicly available in the plugin repository, either OctoPrint-Tasmota or OctoPrint-TPLinkSmartplugs will have the same issue. 

The weird part is, if I refresh and open the settings dialog immediately it has the customization, and then after a background settings change it flips back. I'm going to go ahead and assume it's my plugin that is doing the background setting change when it checks for the current status of the plugs, but I don't change the background-color css style in any of my code.
