### ISSUE TITLE
Compatibility with Tempsgraph 

### ISSUE THREAD

**Issue by BrokenFire** [Birkbjo/OctoPrint-Themeify#12]
It would be nice if you make it compatible whit Tempsgraph (https://github.com/1r0b1n0/OctoPrint-Tempsgraph)
Currently i have an ugly white background on graph:

![](https://image.prntscr.com/image/wo_mvfZSRtuLLu_Cerb-lg.png)

**Comment by Birkbjo** [comment]
I have noticed this as well, however there is no easy fix from my side, as the graph is updating from the JS code, and with a dark background it's very hard to see the legends.

However I will try to contact the developer, and maybe do a pull request to his plugin!

**Comment by JLatasa** [comment]
I have implemented a dark backgound as in the picture below:

![capture](https://user-images.githubusercontent.com/16670235/35433109-83109176-0282-11e8-91b3-c28d0ae13940.PNG)

I dont understand the problem @Birkbjo describes, but from my point of view it looks nice.
I would have no problem to implement if @BrokenFire thinks it is right.

**Comment by Birkbjo** [comment]
I have been looking at the same thing @Jlatasa. I'm working on a PR for the tempsgraph plugin so you can customize the colour for the background and legends.
What I meant is that if you use a darker  background that you chose it's hard to see the legends in the graph  (the text for timestamps and temps).

**Comment by Birkbjo** [comment]
This has now been added to Tempsgraph, so please update and you should be able to customize your background there!

**Comment by JLatasa** [comment]
If you @Birkbjo need to change the color of the leyend (the text for timestamps and temps), you just have to add _color: "new_color"_ inside each axis:

` yaxis: {
     color: '#dadadc',
     ___: _____,
     ___: _____,
}`

  
![imagen](https://user-images.githubusercontent.com/16670235/35535326-764df3e8-0543-11e8-802b-d7c3cd8b58c6.png)

By the way, thank you very much for your nice job!!
