### ISSUE TITLE
Caret color on "Discorded" theme

### ISSUE THREAD

**Issue by appideasDOTcom** [Birkbjo/OctoPrint-Themeify#14]
The carets (drop-down arrows) on the Discorded theme should be white, not black. They are hard to see as-is:

![screen_01](https://user-images.githubusercontent.com/5428893/33821405-89134f1c-de08-11e7-8fc9-fba012b75efd.png)

This would be easy to fix by overriding this rule:
border-top: 4px solid #000;
from the .caret definition in packed_libs.css (change "000" to "FFF").

I have it fixed on my local copy with a "Custom style" rule in Themify's options.

**Comment by Birkbjo** [comment]
Thanks for reporting this. Will be fixed in next release!
