### ISSUE TITLE
[REQUEST] Custom small Icon

### ISSUE THREAD

**Issue by bolsoncerrado** [Birkbjo/OctoPrint-Themeify#15]
Can you add the option (admin setting field) to change the icon on the upper left, aka "brand" icon, too?

in packedcore CSS:

#navbar

....

.brand span {
background-image: url(../img/tentacle-20x20-light.png);
}

**Comment by Birkbjo** [comment]
This can be done with the custom styling.

Go to Themeify-settings, create a new rule and use ".brand span" as the selector, "background-image" as the CSS-rule and the url for the value; ie: url("http://www.freeiconspng.com/uploads/3d-printer-icon-5.png")

<img width="650" alt="screen shot 2017-12-12 at 20 30 42" src="https://user-images.githubusercontent.com/13852438/33904283-64704e34-df7b-11e7-8876-54c01aa8af0b.png">

Results:

<img width="124" alt="screen shot 2017-12-12 at 20 30 47" src="https://user-images.githubusercontent.com/13852438/33904282-64541084-df7b-11e7-86ce-d434926f2825.png">

It would be more work if you want the image hosted offline on the octoprint-instance, but I do not really plan to add an upload feature, if that is what you are asking.

**Comment by bolsoncerrado** [comment]
Awesome!

Thanks!!
