### ISSUE TITLE
[REQUEST] How would I change TAB labels (text format) to ICONS instead?

### ISSUE THREAD

**Issue by bolsoncerrado** [Birkbjo/OctoPrint-Themeify#16]
"Temperature  Control     GcodeViewer ..." 
to display icons instead?

Would it be possible?

**Comment by SebastianSchultz** [comment]
That would  be great! :)

**Comment by Birkbjo** [comment]
This is something that will be very hard / hacky to do just with CSS. I can see what I can do though.

**Comment by Birkbjo** [comment]
I've decided to implement this, should be in the next release sometime this week.

Sneak peak: 
<img width="655" alt="screen shot 2018-04-03 at 01 44 05" src="https://user-images.githubusercontent.com/13852438/38221578-8bec1abc-36e0-11e8-8317-f8899fef48e9.png">

**Comment by Birkbjo** [comment]
This has been implemented now. You may need to update the manual way. Will release a new version soon.
