### ISSUE TITLE
PSU Control Icon same color

### ISSUE THREAD

**Issue by CrEaK** [Birkbjo/OctoPrint-Themeify#2]
Im using the plugin [PSU Control](http://plugins.octoprint.org/plugins/psucontrol/) with your theme, but I found a little visual error. Normally when the PSU is on "active" the Lightning-Icon is green and when "inactive" white. But with your theme on both states are white.

I think you are overwriting the color with:
`i {
  color: #dadadc !important;
}`

**Comment by Birkbjo** [comment]
Right, that was a quick fix to override all icons - but I will look into doing it another way.

Thanks from bringing it to my attention! :)

**Comment by CrEaK** [comment]
Wow, that was fast :D 

No Problem! Thanks for making this very nice looking theme! :)

**Comment by Birkbjo** [comment]
Do you have an easy way to install your plugin in a developer-environment? Or do you develop directly on your pi?

**Comment by CrEaK** [comment]
Im developing directly on my pi, but i can install a snapshot version. no problem

**Comment by Birkbjo** [comment]
Just wondering, since I'm having problem installing it because of needing RPi.GPIO, so currently not able to test it on my dev-environment.

**Comment by Birkbjo** [comment]
This should now be fixed, so if you reinstall the plugin in should be updated to handle that :)

**Comment by CrEaK** [comment]
Its working perfectly now :) Thanks! :+1:
