### ISSUE TITLE
How to use 100% screen width

### ISSUE THREAD

**Issue by FlyingEagle** [Birkbjo/OctoPrint-Themeify#20]
i want to know if it's possible to use the whole screen width instead the maybe 75%.

so i can see more tabs.

**Comment by Birkbjo** [comment]
You can increase width, I don't really know how much more size you would want, but here goes:
Go to Themeify settings, enable customisation, click advanced options and create two new rules

Selector: .span8
CSS-rule: width
Value: 900px

Selector: .container
CSS-rule: width
Value: 1400px

You can change the values according to what you want, but that should give you a starting point.

**Comment by FlyingEagle** [comment]
It works, nearly, but i do see 5 tabs, and 6 more are hidden in the small side menu.
is there a way to prevent hiding tabs in this menu?

**Comment by Birkbjo** [comment]
Seems to work for me, can you show me a screenshot of before and after resizing the window?
