### ISSUE TITLE
Create New Theme

### ISSUE THREAD

**Issue by mrwizerd** [Birkbjo/OctoPrint-Themeify#22]
I am trying to write a new theme and I have cloned  themeify, I have to say I am very new at this and I am sorry if there is a better place to put this but I cant find any other way of communicating.  I created a folder for my theme, copied the files from discorded as a starting spot, renamed it to my theme name and now want to edit the style sheets.  This I can do I know enough about the code to edit colors and such, the problem is, getting it into octoprint.  I assume I could uninstall themeify then install my personal fork.  In that case all I would have to do is get the theme listed in the drop down menu which I think I know where that is, and then edit the .less on the octoprint server and just reload to see changes?  Is that the jist of it? or is there a simpler way of getting all this done.

  I saw that it said if I had set stylesheet = less in the yaml file but I don't see stylesheet anywhere in that file and googled how to add it and could not find anything.  I originally tried to parse out what all the selectors and css rules were to try and do my changes that way but I could not find a list of them anywhere.  I have been googling for hours and creating this issue ticket was my only hope at some help.  I again apologize if this is the totally wrong place to post this.

**Comment by Birkbjo** [comment]
Did you install the plugin into your octoprint instance? First you have to fork the repo, and "cd OctoPrint-Themeify".

`octoprint dev plugin:install`
This should install the plugin, and any changes done to the less files in the fork-folder should be seen in your octoprint instance.

**Comment by mrwizerd** [comment]
Yeah themeify is installed onto the pi using the latest raspbian image.  I
then installed themeify through the plugin manager.  I have checked the
~/.octoprint/themes folder for it but its not there.  I forked themeify
last night and edited the file with the menu.  But cannot find the
OctoPrint-Themeify directory on the pi.

**Comment by Birkbjo** [comment]
I advise you to look at the link and develop on your local machine, much faster that way.

However, if you want to do it on the PI, you can see the path of each plugin that are loaded when octoprint starts (or in the logs). You can also fork my repo on the pi, then cd into that folder and run `octoprint dev plugin:install`. Which will link that directory to your octoprint instance and you can edit the files there and restart octoprint.
