### ISSUE TITLE
how to change the image octopus in octopi using themeify

### ISSUE THREAD

**Issue by amrithmmh** [Birkbjo/OctoPrint-Themeify#24]
used `#navbar .navbar-inner .brand span` as selector
and `background-image` as CSS rule 
for url() what should i give my image is in /home/pi/icon.png
and how to change this <link rel="shortcut icon" href="/static/img/tentacle-32x32.png">image too?

also i would like to change the page before you log in and also after logging in but where is the html files located in Octopi/Octoprint installation (if someone could help me that would be great)

**Comment by Birkbjo** [comment]
If you have internet connection (to the outside world) you can upload your image on any service, like imgur and use the following:
Selector: `#temperature-graph`
CSS Rule: `background-image`
Value: `url("http://theurlhere.com")`

Or, if you want to upload your own image to the PI, the simplest solution is to use this plugin: https://github.com/jneilliii/OctoPrint-CustomBackground.
