### ISSUE TITLE
Can't see "Navbar Temperature Plugin" with Discorded theme

### ISSUE THREAD

**Issue by MrTimcakes** [Birkbjo/OctoPrint-Themeify#25]
Hey,

The Discorded theme makes the navbar a color which doesn't work well with the "Navbar Temperature Plugin". Can that text be changed to say, white?

Thank You.
![onpaste 20180402-224649](https://user-images.githubusercontent.com/3743776/38217990-3d7dc46a-36c8-11e8-84fa-91961805fa22.png)

**Comment by Birkbjo** [comment]
I've posted a solution for this earlier, see this issue: https://github.com/Birkbjo/OctoPrint-Themeify/issues/8

**Comment by MrTimcakes** [comment]
Oh wonderful, sorry should have looked first.

**Comment by Birkbjo** [comment]
No worries! 
Just open another issue if you have any suggestions or feedback!
