### ISSUE TITLE
Themeify ignores settings

### ISSUE THREAD

**Issue by Fivefold** [Birkbjo/OctoPrint-Themeify#28]
Unfortunately, the enable setting (or any other basic setting for that matter) doesn't have any effect. The theme or colours stay the same after saving the plugin settings, i.e. the original Octoprint theme. 

I'm using Themeify 1.2.0 from the bundled plugin manager and Octoprint 1.3.8 on OctoPi 0.14.0 on a Raspberry Pi Model 2B+. Not sure what other relevant info I could give.

**Comment by Birkbjo** [comment]
Can you try to use the latest version directly from master?
Using this link in the download manager: `https://github.com/birkbjo/OctoPrint-Themeify/archive/master.zip`

**Comment by Fivefold** [comment]
The issue persists. I removed the version from the repo, restarted, installed directly from master, restarted (checked the enable setting and saved, too). 

Same behaviour as before. Anything else I can try?

**Comment by Birkbjo** [comment]
Probably some caching issues.
Will push a new version soon, if it's broken I'm the repo
