### ISSUE TITLE
Problem with custom control editor

### ISSUE THREAD

**Issue by devildant** [Birkbjo/OctoPrint-Themeify#31]
Hello,

i create this issue because i found a little problem with templates bellow and plugin custom control editor (inside option) : 
- discorded
-discordedorange
-nighttime

![image](https://user-images.githubusercontent.com/8700106/41098904-2e8c1fec-6a5d-11e8-9bf1-61c4e984ca40.png)
(the text in sub section is black)

style for patch: 
`.custom_section > h1 {
    color: #FFFFFF!important;
}`

**Comment by Birkbjo** [comment]
It's hard to style it according to all templates, that's why you have the ability to style it the way you want with the custom rules, so users can do this themselves. 
However I do have some plans to export and import rules, so users can share these fixes easily.

**Comment by devildant** [comment]
Hello,
Yes, I understand.
I tried the customization before creating this issue, and that did not work.
![image](https://user-images.githubusercontent.com/8700106/42091953-8407afb2-7ba7-11e8-9332-ef650b2e870f.png)

selector : .custom_section > h1
css-rules : color
value : #FFFFFF!important

I do not know what I'm doing wrong

**Comment by Birkbjo** [comment]
Sorry for the late reply. It should work if you remove the "!important" part. The styling are added to the elements, so important is usually not necessary.
