### ISSUE TITLE
[REQUEST] Include default OctoPrint theme

### ISSUE THREAD

**Issue by jneilliii** [Birkbjo/OctoPrint-Themeify#34]
I have had a couple of people want to tweak their UI settings with some of my plugins and am pointing them in the direction of Themeify for these tweaks, like font-family for the M117-NavBar plugin.  The drawback is you can't just tweak advanced settings without enabling an overall theme.  I think it would be good to have the default OctoPrint theme included as part of the options in order to keep the overall look if people want and then they can tweak the advanced section to their hearts content.

**Comment by Birkbjo** [comment]
I will implement the global "Enable" to "Enable Theme", so you can switch this of for the use case you've described. I see no reason to have a global "Enable" switch, as I have that for all the other features, as well as you can disable it from the OctoPrint plugin manager (even though that requires a restart).
