### ISSUE TITLE
Discord Theme wrong colors with OctoLapse

### ISSUE THREAD

**Issue by EpicLPer** [Birkbjo/OctoPrint-Themeify#37]
![image](https://user-images.githubusercontent.com/8442196/43360588-365525ec-92b8-11e8-91e5-018ad1f6a271.png)

**Comment by Birkbjo** [comment]
This styling is probably done by the plugin author. I cannot foresee and update the themes for all plugins there is. Therefore you have the ability to change this yourself in the advanced settings of the plugin. In these case the author has a custom color for ".panel". Just add ".panel" in the selctor of advancded settings, background-color as the rule and "#36393f" as the value (for the same color as the rest).
