### ISSUE TITLE
Custom Style to color scroll bars?

### ISSUE THREAD

**Issue by SillyHats** [Birkbjo/OctoPrint-Themeify#38]
What custom style Selector and CSS-Rule should I use to be able to make the scroll bars match the rest of the theme? 

There is one on the side of the whole page and one on the file list mini-window. There are also less important others such as the octoprint settings overlay window.

**Comment by Birkbjo** [comment]
You can use the selector "-webkit-scrollbar" and "background-color" as rule, with ie. value "#2f3136"
