### ISSUE TITLE
Screenshot "Map" of CSS?

### ISSUE THREAD

**Issue by bolsoncerrado** [Birkbjo/OctoPrint-Themeify#4]
Hi,

Can either you or whoever started uploading alt themes provide a screenshot of which CSS changes what? 

I know most of them are self explanatory but perhaps this eases a quicker way to create new themes for the rest of us by changing what we want where and when we want it ;)

Thanks!

**Comment by Birkbjo** [comment]
My stuff is written in less [here](https://github.com/Birkbjo/OctoPrint-Themeify/blob/master/octoprint_themeify/static/less/themeify.less), I can start commenting it more, but most of it should be pretty explanatory.

You can also use chrome-devtools and inspect the element you want to style, and copy-paste the style-selector. 

I'm also working on creating a "base" file, which can be customized directly from the OctoPrint settings UI.
