### ISSUE TITLE
[Doubt] Remove CSS-rule from selector

### ISSUE THREAD

**Issue by scmanjarrez** [Birkbjo/OctoPrint-Themeify#43]
Hi,
Is it possible to remove CSS-rule from selector? I mean, current CSS of octoprint webpage.
Example: Currently, there is a button with the following style
`style="margin-left: 0px; width: 23%;"`
 I want to remove margin-left from the style, I'm trying using "none"
![image](https://user-images.githubusercontent.com/9284124/46756554-07221600-ccc8-11e8-8393-d1ee009e682f.png)
it works after saving Themify, but after reloading webpage, margin-left goes to 0px again (I guess #29).

**Comment by Birkbjo** [comment]
Use 0px
