### ISSUE TITLE
[Request] Settings option to not colour the navbar?

### ISSUE THREAD

**Issue by ntoff** [Birkbjo/OctoPrint-Themeify#5]
When you get the settings up and running, could we please have an option to not apply the theme to the navbar? I really like the discord theme but I have multiple printers so I have different coloured nav bars for each printer to let me quickly see which printer I'm looking at from a distance.

**Comment by Birkbjo** [comment]
Sure, I'm planning to have a custom configuration for the color of the navbar.

**Comment by Birkbjo** [comment]
This has been added in the latest release, so you should now be able to identify your servers!

**Comment by ntoff** [comment]
cool thanks.
