### ISSUE TITLE
Why browser background white

### ISSUE THREAD

**Issue by Egauss** [Birkbjo/OctoPrint-Themeify#51]
i just installed this theme, and have white browser background and dark theme, anybody know the problem? If i refresh browser it comes as normal all dark and after couple seconds main background comes white again

**Comment by StefanPenkert** [comment]
hi, can you tell me the plugin, hi have the same problem

**Comment by Egauss** [comment]
Mosaic Palette plugin it's for multicolor device

**Comment by StefanPenkert** [comment]
thank you! i have also the palette plugin and now it works

**Comment by Egauss** [comment]
If you have marlin firmware on your printer, probably canvas hub will be useless, as you can't print small round things. Nothing helps only 32bit board
