### ISSUE TITLE
Can't enable (Pi)

### ISSUE THREAD

**Issue by dtest505** [Birkbjo/OctoPrint-Themeify#53]
I've installed on 2 different Pi3's  Last one bone stock. Both running Ethernet, not WiFi.

When I enable the plugin from Themeify option, it doesn't take.  (its enabled in the plugin manager also)  The check mark show it enabled.  I save, then just refresh browser and going back into Themeify, the enable check mark is gone.  Same if I reboot the Pi.  (same if I do all 3 check marks)

Yes, default and no transparent are correct in appearance.
What gives?  Sounds like a permissions issue, but then I shouldn't have been able to install the plugin.

**Comment by theREALaltoid** [comment]
What version of Octopi are you running?

**Comment by dtest505** [comment]
Oh sorry for the lloonngg delay.  For some reason it started working.  But at the time, all latest versions.
