### ISSUE TITLE
Custom Tab Icons Option Not Available on all Octoprint Installation

### ISSUE THREAD

**Issue by kietcallies** [Birkbjo/OctoPrint-Themeify#54]
I am running several Raspberry Pis running Octoprint for several 3D Printers. I have noticed that some of my Octoprint instances running Themeify have the Enable Tab-icons option available and others do not. I have check and all instances are running the most current version of Themeify,

It shows up on an instance running, OctoPrint 1.3.11 running on OctoPi 0.15.1 , but not OctoPrint 1.3.11 running on OctoPi 0.14.0.

**Comment by Birkbjo** [comment]
This is because you have installed from master in some of your instances, and used the plugin manager in others. It's not 'officially' released as I haven't tagged a new version with it.
