### ISSUE TITLE
Feature Request: Update to work in OctoPrint 1.4.x

### ISSUE THREAD

**Issue by PlasmaSoftUK** [Birkbjo/OctoPrint-Themeify#59]
I've just installed OctoPrint 1.4.0rc2 and I notice that Themeify doesn't appear in the list of available Plugins. I love the dark mode and it would stop me updating to this if I couldn't have it. I can see some changes were made for Logging compatibility for Python 3 so Is it just a matter of adding the relevant section to get it to show in the plugin list?

`compatibility:
  python: ">=2.7,<4"`

Thanks
Plasma

**Comment by PlasmaSoftUK** [comment]
I've fixed this an installed manually, it is as simple as adding the following to __init__.py after line 101 ..

`__plugin_pythoncompat__ = ">=2.7,<4"`

Then I did a manual install, if this could be updated and pushed to the Plugin Repository that would be great! :)

Plasma

**Comment by VictorLamoine** [comment]
Already fixed with https://github.com/Birkbjo/OctoPrint-Themeify/commit/fa7e3d1b38055228fd0156ff0df79de64cb7f0b9

This issue can be closed

**Comment by jneilliii** [comment]
Plugin Repository (plugins.octoprint.org) also need to be updated with compatibility flags in order for Plugin Manager to be able to list the plugin in a Python 3 environment. Additional information can be found [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html#telling-octoprint-your-plugin-is-python-3-ready).
