### ISSUE TITLE
Installing v1.2.1 results in only v1.2.0 (causing update version loops)

### ISSUE THREAD

**Issue by gruvin** [Birkbjo/OctoPrint-Themeify#71]
From `grep -ir 'themeify'` ...

```
logs/plugin_pluginmanager_console.log:2020-04-02 11:13:02,950 > Collecting https://github.com/birkbjo/OctoPrint-Themeify/archive/master.zip
logs/plugin_pluginmanager_console.log:2020-04-02 11:13:03,953 > Downloading https://github.com/birkbjo/OctoPrint-Themeify/archive/master.zip
logs/plugin_pluginmanager_console.log:2020-04-02 11:13:07,085 > Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.12.post0.dev0_g8409fda-py2.7.egg (from Themeify==1.2.0) (1.3.12.post0.dev0-g8409fda)
```

Note, 'from Themeify==**1.2.0**', despite using current (2020-04-02NZST) URL `https://github.com/birkbjo/OctoPrint-Themeify/archive/master.zip`

I'm not sure if I'm actually running v1.2.1 and just the version string wasn't changed or if the master branch isn't actually v1.21 ... or what?

Cheers

**Comment by fuyrk** [comment]
confimed

**Comment by jneilliii** [comment]
Looks like version in setup.py wasn't updated...

**Comment by dburr** [comment]
+1
Had to temporarily disable automatic update checking to stop octoprint from bugging me about this every time

**Comment by jneilliii** [comment]
Can't you just click ignore and it will just stop it for that plugin? I'm not sure that's how it works, but I haven't seen the update show up again since I did that.

**Comment by taker218** [comment]
just had a look at the setup.py, it seems like the version was not updated here.

I downloaded the source code, changed the version in the setup.py and installed the plugin via pluginmanager. Now version 1.2.1 is installed

So I guess if you installed the update it should have version 1.2.1 installed, despite the fact that version 1.2.0 is shown. Just ignore the update as @jneilliii  said and it won't bother you till the next release.

**Comment by Birkbjo** [comment]
Sorry, I forgot to update `setup.py` with the tag-version! I've pushed a new version that should fix this.

**Comment by gruvin** [comment]
@Birkbjo  Sweet. :-) Thanks.

**Comment by Birkbjo** [comment]
Fixed in https://github.com/Birkbjo/OctoPrint-Themeify/commit/9a85f727e0855ac4ec6d64868e9a772fab0e233e
