### ISSUE TITLE
Update loop

### ISSUE THREAD

**Issue by fuyrk** [Birkbjo/OctoPrint-Themeify#72]
Unable to update to 1.2.1 from 1.2.0 with octopi 1.4.0
Update runs and completes but after octopi restart themeify is still on 1.2.0 and the update is still available. #71

**Comment by Uwemattes** [comment]
Same on mine!

**Comment by Birkbjo** [comment]
Sorry, I forgot to update `setup.py` with the tag-version! I've pushed a new version that should fix this.

**Comment by gvmturl** [comment]
> Sorry, I forgot to update `setup.py` with the tag-version! I've pushed a new version that should fix this.

Thank you, not solving buy updating... uninstall clear data > Install to solve it. 


Thank you again!
