### ISSUE TITLE
Custom Icons not working with Bed Visualizer Plugin

### ISSUE THREAD

**Issue by chimcen** [Birkbjo/OctoPrint-Themeify#79]
Hi,

thank you for this great plugin.

It works perfect - with one little error:
The custom plugin icon isn't working for Bed Visualizer Plugin.
I've configured it well (like the other plugin icons) - it would be shown in Themeify plugin, but didn't change the text to my defined icon... could anyone help?
![image](https://user-images.githubusercontent.com/22658487/80963000-65649b80-8e0e-11ea-9ca1-09e60edd421b.png)
![image](https://user-images.githubusercontent.com/22658487/80963047-8200d380-8e0e-11ea-8dc7-6705517ce755.png)

Selector: #tab_plugin_bedlevelvisualizer    |    Class: fa fa-connectdevelop

**Comment by tezdal** [comment]
use #tab_plugin_bedlevelvisualizer_link
for any page, use the _link ending even if it is not in the browser

**Comment by chimcen** [comment]
This is the trick - thx bro
