### ISSUE TITLE
Dark theme doesn't get along with navbar temperature display

### ISSUE THREAD

**Issue by Lenbok** [Birkbjo/OctoPrint-Themeify#8]
When I enable themeify (discorded theme), the temperatures reported by the navbar temperature display plugin are no longer visible. With the material light theme they are visible.

I'm not sure whether responsibility for working together nicely lies with the themeify plugin or the navbar plugin.

**Comment by Birkbjo** [comment]
You can either change the Navbar color from the settings of Themeify, or do the following to change the text color for that part:

Go into settings > Themeify > Enable Customization > Click advanced options > New -> type ".navbar-text" as the Selector and "color" as CSS-rule, then select white, or type #ffffff -> Save

See attached screenshot:
<img width="784" alt="screen shot 2017-11-21 at 19 22 45" src="https://user-images.githubusercontent.com/13852438/33089642-91279224-cef1-11e7-960e-cb9de46bf026.png">

**Comment by Lenbok** [comment]
Cool (almost). Any idea why that would work on one of my instances, but the other only partially works?:

![image](https://user-images.githubusercontent.com/282098/33112171-aea02670-cfb6-11e7-8656-6fb7f0c432f5.png)
![image](https://user-images.githubusercontent.com/282098/33112186-be2ea2b0-cfb6-11e7-9d07-a66637c823db.png)

**Comment by Birkbjo** [comment]
Hm. Did you do the same thing? Remember to enable to rule with the checkbox.

**Comment by Lenbok** [comment]
Weird, now both of them are only applying the white color to the bed temperature, and I don't think I changed anything! Both browsers I've tried look the same (chromium and firefox)

![image](https://user-images.githubusercontent.com/282098/33141722-e2ac9086-d018-11e7-9951-f88539bee0fa.png)

I'm no web dev, but the  inspector looks like this:

![image](https://user-images.githubusercontent.com/282098/33141846-531cb68e-d019-11e7-8660-7824498e485f.png)

I looks like white has been applied to the bed but not the tool.

**Comment by Lenbok** [comment]
More information - when I click the checkbox to apply the custom navbar-text color, the color is applied to both entries in the nav bar, but if I reload the page in the browser, it is only applied to the bed color. Maybe some kind of race condition during plugin initialization when the page is loaded?

**Comment by Birkbjo** [comment]
Thanks for the info, I think I've identified the issue. I apply the CSS-rules before some elements are loaded, will be patched soon!

**Comment by Birkbjo** [comment]
If you want it now, you can try reinstalling the plugin with the link under the setup section of the readme.

**Comment by Lenbok** [comment]
That seems to have sorted it. If I've installed via the link, how does that interact with getting updates via the normal octoprint update mechanism?

**Comment by Birkbjo** [comment]
It should be fine. You will most likely get an update notification when I push the changes, because the version is not updated yet.
Still looking at some other minor fixes that I will do before I push it though.
