### ISSUE TITLE
Themeify not working on Raspberry PI Touchscreen

### ISSUE THREAD

**Issue by realbadfox** [Birkbjo/OctoPrint-Themeify#99]
Hello,

I am using Themeify on my Octoprint and it is really great.,

It works on the webinterface via PC or Smartphone, but it doesn't work on my Raspberry PI Touchscreen.

I click on enable and restart, but it has no effect and the original theme is visualized.

can you help me please?

yours chris

**Comment by Birkbjo** [comment]
It's very hard for me to support you here as I don't have a Raspberry touchscreen. Did you get any errors in your console?

**Comment by realbadfox** [comment]
now its working with chromium and autostart. And I removed TouchUI!
